import { NextResponse } from "next/server";
import { createServiceClient } from "@/lib/supabase/server";
import { stripe } from "@/lib/payments";
import { env, stripeConfigured } from "@/lib/env";
import { shortCode } from "@/lib/utils";
import { queuePassDelivery } from "@/lib/whatsapp";
import type { Database } from "@/lib/database.types";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";

type OrderRow = Pick<
  Database["public"]["Tables"]["orders"]["Row"],
  "id" | "buyer_id" | "event_id" | "status" | "buyer_phone" | "buyer_name"
>;
type OrderItemRow = Pick<Database["public"]["Tables"]["order_items"]["Row"], "tier_id" | "quantity">;
type PassInsert = Database["public"]["Tables"]["passes"]["Insert"];

/**
 * Transition the order to `paid` and generate one pass per ordered seat.
 *
 * This mirrors the logic in `app/api/checkout/[orderId]/confirm/route.ts` so
 * that the Stripe path and the mock path produce identical results.
 *
 * Idempotency: if the order is already `paid` we return without re-processing
 * so Stripe webhook retries do not create duplicate passes.
 */
async function fulfillOrder(
  service: Awaited<ReturnType<typeof createServiceClient>>,
  orderId: string,
  paymentRef: string,
): Promise<void> {
  const { data: orderRaw, error: orderError } = await service
    .from("orders")
    .select("id, buyer_id, event_id, status, buyer_phone, buyer_name")
    .eq("id", orderId)
    .single();

  if (orderError || !orderRaw) {
    throw new Error(`Order ${orderId} not found: ${orderError?.message ?? "unknown"}`);
  }

  const order = orderRaw as OrderRow;

  // Idempotency guard — Stripe retries webhooks; do not double-process.
  if (order.status === "paid") {
    return;
  }

  // Only `pending` orders may transition to `paid`. If the order is in any
  // other terminal state (cancelled, refunded, etc.) leave it alone.
  if (order.status !== "pending") {
    console.warn(
      `[stripe webhook] Order ${orderId} is in status '${order.status}', skipping fulfillment`,
    );
    return;
  }

  // Conditional update — only flip pending → paid. If another process (e.g.
  // the /confirm endpoint after a successful return-from-Stripe redirect) has
  // already marked it paid, the .eq("status", "pending") filter will match 0
  // rows and we should not generate passes.
  const { data: updatedRaw, error: updateError } = await service
    .from("orders")
    .update({
      status: "paid",
      payment_provider: "stripe",
      payment_ref: paymentRef,
      updated_at: new Date().toISOString(),
    })
    .eq("id", orderId)
    .eq("status", "pending")
    .select("id");

  if (updateError) {
    throw new Error(`Failed to mark order paid: ${updateError.message}`);
  }

  const updated = (updatedRaw ?? []) as { id: string }[];
  if (updated.length === 0) {
    // Another worker won the race — assume passes are being / have been
    // generated by them and bail out.
    console.info(`[stripe webhook] Order ${orderId} already transitioned, skipping pass generation`);
    return;
  }

  const { data: itemsRaw, error: itemsError } = await service
    .from("order_items")
    .select("tier_id, quantity")
    .eq("order_id", orderId);

  if (itemsError) {
    throw new Error(`Failed to load order items: ${itemsError.message}`);
  }

  const items = (itemsRaw ?? []) as OrderItemRow[];
  if (!items.length) {
    console.warn(`[stripe webhook] Order ${orderId} has no items`);
    return;
  }

  const passInserts: PassInsert[] = items.flatMap((item) =>
    Array.from({ length: item.quantity }, () => ({
      order_id: orderId,
      event_id: order.event_id,
      tier_id: item.tier_id,
      holder_name: order.buyer_name ?? null,
      code: shortCode(),
      status: "valid" as const,
    })),
  );

  const { data: passesRaw, error: passError } = await service
    .from("passes")
    .insert(passInserts)
    .select("id");

  if (passError) {
    throw new Error(`Failed to insert passes: ${passError.message}`);
  }

  const passes = (passesRaw ?? []) as { id: string }[];

  // Queue WhatsApp delivery for each pass. We swallow per-pass errors so a
  // Twilio outage / misconfiguration does not cause Stripe to retry the
  // webhook (which would re-attempt fulfillment via the idempotency guard,
  // but is still wasteful).
  if (order.buyer_phone) {
    for (const pass of passes) {
      try {
        await queuePassDelivery(pass.id, order.buyer_phone);
      } catch (waErr) {
        console.error("[stripe webhook] WhatsApp queue failed for pass", pass.id, waErr);
      }
    }
  }
}

export async function POST(request: Request) {
  if (!stripeConfigured) {
    return NextResponse.json({ error: "Stripe not configured" }, { status: 503 });
  }

  if (!env.STRIPE_WEBHOOK_SECRET) {
    console.error("[stripe webhook] STRIPE_WEBHOOK_SECRET not set");
    return NextResponse.json({ error: "Webhook secret not configured" }, { status: 503 });
  }

  // IMPORTANT: read the raw body as text — Stripe signature verification
  // requires the exact bytes Stripe sent. Do NOT use request.json().
  const rawBody = await request.text();
  const sig = request.headers.get("stripe-signature");

  if (!sig) {
    return NextResponse.json({ error: "Missing Stripe signature" }, { status: 400 });
  }

  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  let event: any;
  try {
    event = stripe().webhooks.constructEvent(rawBody, sig, env.STRIPE_WEBHOOK_SECRET);
  } catch (err) {
    console.error("[stripe webhook] Signature verification failed", err);
    return NextResponse.json(
      { error: err instanceof Error ? err.message : "Webhook signature verification failed" },
      { status: 400 },
    );
  }

  const service = await createServiceClient();

  try {
    switch (event.type) {
      case "checkout.session.completed": {
        const session = event.data.object as {
          id: string;
          metadata?: { order_id?: string } | null;
          client_reference_id?: string | null;
          payment_status?: string;
        };

        // Only fulfill if Stripe actually collected payment. For
        // mode: "payment" checkout sessions this is typically "paid"
        // by the time we receive checkout.session.completed.
        if (session.payment_status && session.payment_status !== "paid") {
          console.info(
            `[stripe webhook] Skipping session ${session.id} with payment_status=${session.payment_status}`,
          );
          return NextResponse.json({ received: true });
        }

        const orderId = session.metadata?.order_id ?? session.client_reference_id ?? undefined;
        if (!orderId) {
          // Stripe should not retry on 200 — log loudly and ack so we don't
          // retry forever on a malformed session.
          console.error(
            "[stripe webhook] checkout.session.completed missing order_id metadata",
            session.id,
          );
          return NextResponse.json({ received: true, warning: "missing order_id" });
        }

        await fulfillOrder(service, orderId, session.id);
        break;
      }

      case "payment_intent.payment_failed": {
        const intent = event.data.object as {
          id: string;
          metadata?: { order_id?: string } | null;
        };
        const orderId = intent.metadata?.order_id;
        if (orderId) {
          await service
            .from("orders")
            .update({ status: "cancelled", updated_at: new Date().toISOString() })
            .eq("id", orderId)
            .eq("status", "pending");
        }
        break;
      }

      default:
        // Acknowledge other event types we don't currently handle.
        break;
    }
  } catch (err) {
    console.error("[stripe webhook] Handler error", err);
    // Return 500 so Stripe retries — the fulfillment is idempotent.
    return NextResponse.json(
      { error: err instanceof Error ? err.message : "Webhook handler failed" },
      { status: 500 },
    );
  }

  return NextResponse.json({ received: true });
}
